export * from '@/pages/dashboard/home'
export * from '@/pages/dashboard/berkasRutin'
export * from '@/pages/dashboard/petugasUkur'
export * from '@/pages/dashboard/petugasSPS'
export * from '@/pages/dashboard/pegawai'
export * from '@/pages/dashboard/laporan'
